### ISSUE TITLE
Writing ZIP files

### ISSUE THREAD

**Issue by brainboutique** [jimmywarting/StreamSaver.js#119]
Example at zip-stream.js is really neat and helped a lot. Though noticed two isses that others may run into as well:

a) On Windows all ZIPs appear empty BUT the file size is reasonable. After digging a bit: Windows is confused by file and folder names starting with a "/". If you omit these, ZIPs work perfectly on Windows.

b) I believe there is an issue with closing the stream: I believe this should happen after the resource was streamed completely - apparenly only causing issues for larger files:
```js
            ctrl.enqueue({ name, stream })
            ctrl.close()
```
I solved this via Promise.

PS: Great work, would strongly encourage to merge this into the library ;-)

**Comment by jimmywarting** [comment]
Thanks for reporting that.  Nobody have reported issues with windows and I have never tried windows since i only run on Mac.

A: might or might not change how the zip lib works and just leave that up to the developer to do what is right instead. maybe will throw error if it starts with `/`

B: hmm, should be fine to close it once everything is enqueue, then again i simulate some things since i didn't use writableStream (for a reason) and the controller isn't a real stream controller
