### ISSUE TITLE
StreamSaver.js for Cordova

### ISSUE THREAD

**Issue by rachitpant** [jimmywarting/StreamSaver.js#122]
Referencing #120 and asking a new question since thats closed. Just saw your response to question #120 . Was a little happy since I finally was able to save to android , but realized after reading your response that `response.data` is actually all in memory and not streaming.

Fetch might be a little tricky to implement , since I would have to manually set the cross-origin tokens. 

Right now I used [cordova-plugin-file ](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/)to write to device. Will  I have to use both streamsaver and this plugin to be able to stream a file download , rather than writing from a buffer like I am doing now.
```js
    downloadFile (key) {
      axios
        .get(
          `eventdirect/storage/downloadnewer/`,
          {
            responseType: 'blob',
            params: {
              key
            }
          }
        )
        .then(response => {
          function writeFile (fileEntry, dataObj) {
            // Create a FileWriter object for our FileEntry (log.txt).
            fileEntry.createWriter(function (fileWriter) {
              fileWriter.onwriteend = function () {
                console.log('Successful file write...')
              }

              fileWriter.onerror = function (e) {
                console.log('Failed file write: ' + e.toString())
              }

              fileWriter.write(dataObj)
            })
          }
          window.resolveLocalFileSystemURL(cordova.file.externalDataDirectory, function (fs) {
            console.log('file system open: ' + fs.name)
            fs.getFile('EA25new.pdf', { create: true, exclusive: false }, function (fileEntry) {
              writeFile(fileEntry, response.data)
            }, function (err) { console.error('error getting file! ' + err) })
          }, function (err) { console.error('error loading file system! ' + err) })
        })
        .catch(error => {
          console.log('There was an error:', error.response)
        })
    }
```
I wasn't even aware of the FileSystem API's and hence my question is very basic. Do I have to use the Streaming.js library to stream , or do you think the cordova plugin can handle that. Or do I have to use both of them together. Can you give me any suggestions on how I should proceed. On the server , I am sending a spring boot ResponseEntity<StreamingResponseBody> with the content disposition header , but I have noticed even if I do not add the content disposition header , the above code  writes the file correctly and I can open it. ( During debugging the response disposition type was application/xml when I was not set ).

**Comment by jimmywarting** [comment]
> Referencing #120 and asking a new question since thats closed. 

closed it since there where no issue with streamsaver, (same with this) 
but you can still comment in the same thread, and i can try my best to help you.

> but realized after reading your response that response.data is actually all in memory and not streaming.

That's how axios works, but it's different for node. only way you will get streaming in web/cordova is if you use the fetch api. (there are other solution too, partal request and custom socket streaming - but that is more annoying)

> Fetch might be a little tricky to implement, since I would have to manually set the cross-origin tokens.

axios should be no different from using fetch axios might use XHR or fetch internally in the core.

> Right now I used cordova-plugin-file to write to device. Will I have to use both streamsaver and this plugin to be able to stream a file download , rather than writing from a buffer like I am doing now.

a bit surprised ppl still use cordova instead of things like PWA...

Since you are using cordova... then i would try to use some native background download manager plugin. it will "persists beyond app termination, runs in the background and continues even when the user closed/suspended the application" it's also going to write directly to the phone.

then you probably don't need cordova-plugin-file or streamsaver.

---

If you stream the response back then you can write direct to the cordova-file-plugin something along this lines without using Streaming.js:

```js
fileEntry.createWriter(async function(fileWriter) {
  const res = await fetch(request)
  const readableStream = res.body
  const reader = readableStream.getReader()
  const ws = new WritableStream({
    write (chunk) {
      fileWriter.write(chunk)
    }
  })
  readableStream.pipeTo(ws)  
  }
}, console.error)
```

(don't know how much of it works in cordova... requires some new avalible api's)


> On the server , I am sending a spring boot ResponseEntity with the content disposition header , but I have noticed even if I do not add the content disposition header , the above code writes the file correctly and I can open it. ( During debugging the response disposition type was application/xml when I was not set ).

don't know how file download works in cordova exactly but basically you can't use any ajax library (axios) that uses fetch or XHR. the request have to be navigated to by replacing curent location or open up a new tab/window (or another browser in cordova?)

>  if I do not add the content disposition header , the above code writes the file correctly and I can open it

that's usually whats happen when you have a mimetype that browser can't handle/render

**Comment by rachitpant** [comment]
Thanks for your help in both the threads and for writing this library.
