### ISSUE TITLE
get the download progress

### ISSUE THREAD

**Issue by juniuo** [jimmywarting/StreamSaver.js#129]
Hi jimmywarting:
I have a problem: How can I get the download progress when I download files，I want to monitor the download progress and show it， Do you have any good idea?  thank you.

**Comment by jimmywarting** [comment]
Do you want to show it on the page or native?

if it's native then you need to get the size beforehand somehow
```js
  const res = await fetch(url)
  const fileStream = streamSaver.createWriteStream('filename.txt', {
    size: res.headers.get('content-length') // (in bytes) will show native progress bar
  })
  res.body.pipeTo(fileStream)
```

otherwise 

you could use something like a transform stream to pipe the data and read how much you have piped

```js
var size = 333
var downloaded = 0

var progress = new TransformStream({
  transform (chunk, ctrl) {
    downloaded += chunk.byteLength 
    ctrl.enqueue(chunk)
  }
})

res.body
  .pipeThrough(progress)
  .pipeTo(fileStream)
```

you could also do it without a transform stream and count how many bytes you have written when use use the writer

**Comment by juniuo** [comment]
Thank you very much. Yes, I need to show the download progress of the file on the page.
