### ISSUE TITLE
Windows Defender RAM usage when using StreamSaver

### ISSUE THREAD

**Issue by pcezar-i9** [jimmywarting/StreamSaver.js#133]
Our project uses streamSaver to download huge tiff files (sometimes with 9gb). Some users have been reporting that, while the download is ongoing, Windows Defender starts to build up his RAM usage, sometimes reaching 8gb or more. When download is finished, RAM is released. Other users have no problem whatsoever. Probably this has to do with some Antivirus policy but is weird that withing the same Company structure different results are happening. Has anyone found something like this?

Our implementation is almost identical to your fetch example.

I also have a question that has nothing to do with the topic above. Is it possible to detect if the dowload fails for some reason (fail on backend during the download)? Our filesystem is not of the most reliable, specially with these large files, and some times the download fails. We would like to show some message if this occurs.

**Comment by jimmywarting** [comment]
I haven't had anyone reporting some memory problem with regards to antivirus programs. So i don't know how to help you in that regards. It dose sound like the problem lies in the window defender and that it dose not handle large files in a good way.

---

It certainly is possible to recover a interrupted download and detect it. but then your server also need to support partial request/response https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range to be able to recover.

here is an rough example using pipes (note that it's untested and may not work correctly)
you should handle request attempts and some network error states like not found, no network connection and some other.

```js
const fileStream = streamSaver.createWriteStream('example.bin')
const writer = fileStream.getWriter()

// create a recursive function for to handle interupted downloads
function download(url, bytesWritten = 0) {
  const res = await fetch(url, {
    headers: {
      // start downloading from an offset
      range: bytesWritten + ''
    }
  })
  
  console.log(res.ok, res.status)
  
  res.body.pipeTo(new WritableStream({
    write(chunk) {
      console.log("Chunk received", chunk)
      
      // track how much you have downloaded
      // (you can also show a progress bar by using this)
      bytesWritten += chunk.byteLength

      // pass data along to streamsaver
      writer.write(chunk)
    },
    close() {
      console.log("All data successfully read!")

      // close streamsaver
      writer.close()
    },
    abort(e) {
      console.error("Something went wrong!", e)

      // trying to recover
      download(url, bytesWritten)
    }
  }))

  download(url, bytesWritten).catch(maybeTryAgain)
}

download(url)
```

it's also possible to do `reader = res.body.getReader()` and use the promise based approach to  get a wider browser support that don't yet have `pipeTo` & `WritableStreams` support yet.
