### ISSUE TITLE
Resource interpreted as Document but transferred with MIME type application/octet-stream

### ISSUE THREAD

**Issue by jordpo** [jimmywarting/StreamSaver.js#141]
Hi! 

We're seeing this warning in Chrome (latest). I'm wondering should we just update the `Content-Type` [here](https://github.com/jimmywarting/StreamSaver.js/blob/9871d959c6e243e333c45a3eef0903f9e1912485/sw.js#L91)?

Is this a warning others have seen and dealt with differently, and is it a warning that we should worry about?

**Comment by jimmywarting** [comment]
What warning? haven't seen one...
i have heard that chrome have started to warn about insecure downloads doe...  https://chromeunboxed.com/chrome-mixed-content-blocking-non-secure-downloads-google-developers/

should maybe not affect you if you are using https... might even see streamsaver as an potential workaround for avoiding that download warning as everything passes throught a http -> https connection 

----

if you are referring to: `Resource interpreted as Document but transferred with MIME type application/octet-stream:` then you can just safely ignore it as it's a way to trick browser to just download the content instead of showing the result in an iframe. (if it can't be understood/rendered then it will download it - hence the warning)

**Comment by jordpo** [comment]
Thank you! Yeah that was the warning we were seeing and sounds good that we can ignore it.
