### ISSUE TITLE
Download large objects from AWS S3

### ISSUE THREAD

**Issue by murtazaqa** [jimmywarting/StreamSaver.js#151]
Hi,

I am trying to download a large file (1 GB+) through browser from AWS S3 using the `getObject()` of [aws-sdk-js](https://www.npmjs.com/package/aws-sdk).

Is it possible, using StreamSaver to save the BLOB that I receive as response directly to file-system. Since the file is large, I want avoid the BLOB getting downloaded in browser memory. High possibility of crashing the browser.

I am aware of file-saver.js but it won't help my cause. 

Any help is appreciated. Thanks.

P.S. - I cannot use pre-signed URL.

**Comment by jimmywarting** [comment]
hmm, investigated a bit how aws works, it seems they use XHR in the browser and not fetch.
so it seems like there is no way to get a readable stream from the js sdk in the browser.

if you download it as a blob (or arraybuffer) then you have already everything in the memory so using either streamsaver or filesaver won't do much difference. 

So my initial thoughts are - you have to make the request yourself. That would probably mean you would have to use pre-signed URL, but i don't know the reason why you can't use pre-signed urls...

---

was a long time since i dealt with aws-js-sdk myself and i don't remember so much. but i remembered that there lib where very huge and didn't work in web workers where xml isn't available.
it lowered the score of my PWA for being huge and slow to parse. uses a bunch of node stuff that could be discarded if they followed this [best practices](https://github.com/cross-js/cross-js)

maybe you could investigate using the REST api and do stuff yourself.

**Comment by murtazaqa** [comment]
Hi,

Thanks for quick response, your answer helped me understand further on why it is not possible to get a readable stream on the browser. 

I cannot use pre-signed URL because of security reasons.

Now, I am investigating the option to download using REST API. I will update here if it helps.

Thank you once again.

**Comment by jimmywarting** [comment]
No problem, good luck to you also.

I'm sure others would like to see a example of how to use AWS rest api (including myself)
don't want to have ~250kb added and for it to be restricted to main thread just to download something from AWS.

I Would put up a demo/example of it if you can figure out how to do it (unless you don't make a PR)

**Comment by jimmywarting** [comment]
did you figure something out?

**Comment by murtazaqa** [comment]
Hi Jimmy,

I am sorry for such a delayed response on this. 

Tried downloading from s3 using REST API, did not help us. It is working same as SDK, downloading in the browsers memory as a BLOB.

Thanks.
