### ISSUE TITLE
type definition request

### ISSUE THREAD

**Issue by WaseemRakab** [jimmywarting/StreamSaver.js#160]
hello
I'd like to see type definitions support being added for typescript.
so i could use this package in Angular.
thank you.

**Comment by jimmywarting** [comment]
Is something missing?

I'm not a fan of TypeScript since it don't run anywhere without being transpiled first. 
- You can't simply import the things you want directly in browser with `<script type="module">`
- Often it becomes bundled and minified when you use some kind of build tool (but not always)
- If you bundle things together (which often happens with build tools), then it makes it a bit awkward to lazy load stuff and only import the parts that you just need
- it adds extra compiling time

However, I do see the value in type definitions and i think it's good. That's why i try to use jsDoc annotation and sometimes using default parameters in a good way to to support typescript developers too.

it seems Visual studio code can handle it well:

![Skärmavbild 2020-05-22 kl  02 49 38](https://user-images.githubusercontent.com/1148376/82619707-f2fa0680-9bd6-11ea-9596-83d1822158bf.png)

Streamsaver just have one function basically and that's `createWritableStream` which returns a native WritableStream.

**Comment by jimmywarting** [comment]
could you share some of the "error" or "any" messages you get?

**Comment by WaseemRakab** [comment]
everything is working fine and well in normal vanilla js, but i cannot use it in Angular environment, which needs type definitions for typescript.
for example file-saver has @types/file-saver package which works in angular
again, thank you for your work.

**Comment by ennmichael** [comment]
@jimmywarting Currently, if you install the streamsaver module from npm, TypeScript will error whenever you try to import it because there is no type definition file. (This is just how TypeScript normally works.) This is solved by declaring a streamsaver module in a d.ts file, which will work, but you won't get any type support.

The idiomatic place to add third party type definitions is the [DefinitelyTyped](https://definitelytyped.org/) repository. I am currently in the process of writing a DefinitelyTyped entry for StreamSaver! I will let you know when I'm done (which should hopefully be very soon, I only saw this issue today).

**Comment by ennmichael** [comment]
The PR to add type definitions has been [opened](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45200). Once this gets approved, you'll be able to install them using
```
npm install @types/streamsaver --save-dev
```

**Comment by ennmichael** [comment]
The PR has been merged! You can now install types using the above command. This issue can be closed now.
