### ISSUE TITLE
what should i do if i can not connect to  github.io 

### ISSUE THREAD

**Issue by zetianul** [jimmywarting/StreamSaver.js#165]
Our clients's network is not good enough to connect to https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=2.0.0 successfully , what should i do to get over it ?

**Comment by jimmywarting** [comment]
try hosting `mitm.js` + `sw.js` on your own domain and change the path `streamsaver.mitm = https://example.com/mitm.html`

Alternativ could be to use my newly built [Native-file-system-adapter](https://github.com/jimmywarting/native-file-system-adapter) it borrows some techniques from StreamSaver's service worker by passing all data to a self hosted service worker and download files in the same way. except it don't use mitm and service worker are optional since it can refer to using native option instead if it's avalible

**Comment by zetianul** [comment]
> try hosting `mitm.js` + `sw.js` on your own domain and change the path `streamsaver.mitm = https://example.com/mitm.html`
> 
> Alternativ could be to use my newly built [Native-file-system-adapter](https://github.com/jimmywarting/native-file-system-adapter) it borrows some techniques from StreamSaver's service worker by passing all data to a self hosted service worker and download files in the same way. except it don't use mitm and service worker are optional since it can refer to using native option instead if it's avalible or using a in memory fallback

thx for your reply !! 
i try to change streamSaver.mitm directly like this 
`streamSaver.mitm = 'http://10.120.112.242:8000/Desktop/test.html`
i copy the content of mitm.html into test.html , but this didn't work. The popup won't close automatically.I was wondering why , protocal or sth else?

**Comment by jimmywarting** [comment]
Hmm, you can't host the mitm + sw.js on a insecure domain. Service Worker only works on [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)

The StreamSaver lib itself can work on insecure domains since it communicate via a iframe/popup to something that is hosted on secure domains, that's the reason why i built it as some kind of "man in the middle" to work around some quirks when it comes to installing service workers and making it work via iframes or popups too

it's also possible to configure your browser to treat `http://10.120.112.242:8000` as it where secure

**Comment by jimmywarting** [comment]
If you are like most other people that use StreamSaver for the wrong purpose: fetching something from the cloud and then save it using client side code... Then use server techniques yourself and respond with content-disposition attachment header instead of trying to emulating it using service worker

**Comment by zetianul** [comment]
> If you are like most other people that use StreamSaver for the wrong purpose: fetching something from the cloud with ajax and then save it using client side code... Then use server techniques yourself if you can and respond with content-disposition attachment header instead of trying to emulating it using service worker

My application background is that client has multiple files  and supposed to download as one zip . If i archive files in the browser , the file downloading starts when all the files are archived, that takes some time. So I want to archive in the server side and send chunks to the client side while archiving. But i found out even server has sent chunks to browser , browser still started downloading after receiving all the chunks . I have searched many ways , streamSaver is the only way i have found out which could start downloading by the time broswer start receiving data from server . Here is my code 

server side (koa2): 
`
     const archive = archiver('zip', {
        zlib: { level: 1 }, // Sets the compression level.
      });

      const zippedFilename = 'test.zip';
      const header = {
        'Content-Type': 'application/octet-stream',
        Pragma: 'public',
        Expires: '0',
        'Cache-Control': 'private, must-revalidate, post-check=0, pre-check=0',
        'Content-disposition': `attachment; filename="${zippedFilename}"`,
        'Transfer-Encoding': 'chunked',
        'Content-Transfer-Encoding': 'binary',
      };
      ctx.res.writeHeader(200, header);
      const { fileList } = ctx.request.body;
      let counts = fileList.length;
      archive.store = true;

      fileList.forEach(({ name, url }) => {
        axios.get(url, { responseType: 'arraybuffer' }).then((res) => {
          const buf = Buffer.from(res.data); //eslint-disable-line
          archive.append(buf, {
            name,
          });
          counts--;
          if (counts === 0) {
            archive.finalize();
          }
        });
      });

      ctx.body = archive;
      ctx.attachment(zippedFilename);

      archive.on('error', (err) => {
        throw err;
      });
      archive.on('finish', (ret) => {
        return ctx.res.end();
      });
`
client side: 
`
    fetch('/file/downloadAll',{
      method:'POST',
      headers:{
        'content-type':'application/json',
      },
      body: JSON.stringify({
        fileList,
      })
    }).then((res) => {
      const fileStream = streamSaver.createWriteStream('test.zip');
      res.body.pipeTo(fileStream).then((...rest)=>{
          console.log('finished');
      });
    });
`
This is the only way I am satisfied yet , I was wondering if there are better ways to do so. Thank you for your patience :-)

**Comment by jimmywarting** [comment]
Well, if you do it server side and want to skip streamsaver all togheter then you can't unfortunately use ajax. ajax download don't care about content-disposition and won't trigger a download

downloads only happens when browser are incompatible of rendering a page, and you guessed it, ajax don't render stuff on the page

You have to navigate or open it some how - easiest would be a hidden iframe or just navigating to it using a `<a href="url?filelist=..." download="test.zip">`. but since are sending a fileList using a POST method then you can create a URLEncoded `<form>` it can be hidden if you want.

```html
<form hidden method="POST" action="/file/downloadAll">
  <input type="hidden" name="fileList" value="...">
</form>
```
then you must trigger the submit action to make a navigation happening, that's the only way browser will trigger the download. 

I'm pretty sure it won't take you to the `/file/downloadAll` page when you submit the form since browser is incapable of rendering a zip file so it will just download it and stay on the page you are on.

then you will also have to parse the request body in some other way than application/json. multipart/formdata is mostly for file upload and requires some extra lib like busboy to parse it.
but URLEncoded is easier, you fetch the hole body and use node's built in URLSearchParams to decode it

```js
var query = new URLSearchParams("hole request body as string")
var fileList = JSON.parse(query.get('fileList'))
```
(unless you have some other fancy middleware to do it for you)

**Comment by zetianul** [comment]
> Well, if you do it server side and want to skip streamsaver all togheter then you can't unfortunately use ajax. ajax download don't care about content-disposition and won't trigger a download
> 
> downloads only happens when browser are incompatible of rendering a page, and you guessed it, ajax don't render stuff on the page
> 
> You have to navigate or open it some how - easiest would be a hidden iframe or just navigating to it using a `<a href="url?filelist=..." download="test.zip">`. but since are sending a fileList using a POST method then you can create a URLEncoded `<form>` it can be hidden if you want.
> 
> ```
> <form hidden method="POST" action="/file/downloadAll">
>   <input type="hidden" name="fileList" value="...">
> </form>
> ```
> 
> then you must trigger the submit action to make a navigation happening, that's the only way browser will trigger the download.
> 
> I'm pretty sure it won't take you to the `/file/downloadAll` page when you submit the form since browser is incapable of rendering a zip file so it will just download it and stay on the page you are on.
> 
> then you will also have to parse the request body in some other way than application/json. multipart/formdata is mostly for file upload and requires some extra lib like busboy to parse it.
> but URLEncoded is easier, you fetch the hole body and use node's built in URLSearchParams to decode it
> 
> ```js
> var query = new URLSearchParams("hole request body as string")
> var fileList = JSON.parse(query.get('fileList'))
> ```
> 
> (unless you have some other fancy middleware to do it for you)

many thanks!! perfect solution for me.

**Comment by jimmywarting** [comment]
Glad i could help, FileSaver, StreamSaver, Native File System and `a[download]` alike are mostly built for saving client generated content such as saving a web cam recording, editing a photo and save it without having to upload it to the server and other file conversion that is capitabel of happening inside the browser. or using stuff like WebTorrent.

is it from the cloud, use content-disposition attachment header and make a navigation. don't use any javascript solution for that.

**Comment by kjt1175-create** [comment]
hi

**Comment by kjt1175-create** [comment]
hi roman
