### ISSUE TITLE
Usage of StreamSaver on a closed network and self-signed certificate

### ISSUE THREAD

**Issue by ivospinheiro** [jimmywarting/StreamSaver.js#166]
Is it possible to use **StreamSaver** on closed network (no access to internet) and a self-signed certificate?

If I'm not wrong **StreamSaver** uses internally **Service Workers** to do the file download, which implies to have a Secure connection. The workaround found on **StreamSaver** has been serving the mitm.html and sw.js directly from **github**. Since in my case the application is accessed on a closed network, it will not work.

I've managed to add mitm.html and sw.js files to my application, but since it uses a self-signed certificate it is not possible to register the service worker.

I've checked the code and it seems there are two alternatives using iframe and a popup windows. What are the differences? Could the popup option be a possible solution?

**Comment by jimmywarting** [comment]
> I've checked the code and it seems there are two alternatives using iframe and a popup windows. What are the differences? Could the popup option be a possible solution?

There is no real difference, the iframe and the popup open up the same html file. The iframe is the preferred method of choice and it's used when your domain is secure as well, otherwise if you your domain is insecure then the streamsaver/mitm will open up a popup to a secure domain (github.io) in order to start communicating to the service worker with postMessage

otherwise you would get mixed content warning for having secure features inside an insecure domain... popup's don't applies to this constraint but you are still able to communicate with it using postMessage. 
(all doe the popup is immediately closes since it gets a binding to service worker by transferring a messageChannel port around)

---

> it uses a self-signed certificate it is not possible to register the service worker.

now for your case, i couldn't do it any better then to refer you to this SO question https://stackoverflow.com/questions/38728176/can-you-use-a-service-worker-with-a-self-signed-certificate 

you can set a domain to be treated as secure in your browser settings. localhost and 127.0.0.1 is also treated as secure.

---

If you are like most other ppl that fetch something from a server and download things, read 3 comments starting from this:
https://github.com/jimmywarting/StreamSaver.js/issues/165#issuecomment-645265053

---

an alternative option is to use blobs, object urls and `a[download]` - aka: [FileSaver.js](https://github.com/eligrey/FileSaver.js/)

**Comment by ivospinheiro** [comment]
@jimmywarting about this comment:
>If you are like most other ppl that fetch something from a server and download things, read 3 comments starting from this:
#165 (comment)
In my case I'm trying to download a file from the server, but in my case I need to add an authorization header with the bearer token in order to be able do do the file download.

>an alternative option is to use blobs, object urls and a[download] - aka: FileSaver.js
The problem with FileSaver.js is mostly the file size and the fact that the download is firstly made in memory then it is saved. It could affect the user interaction with the page.

[Native File System](https://wicg.github.io/native-file-system/) could be the solution that I need, but unfortunately it is still on trial.

Many thanks

**Comment by jimmywarting** [comment]
Native File System 
it's possible to enable trial but this will only work in chrome - also this is a power user function too, so you need a valid cert for this also

fiy - i did develop a adapter/polyfill for this also: https://github.com/jimmywarting/native-file-system-adapter
