### ISSUE TITLE
Download only works once in insecure context

### ISSUE THREAD

**Issue by Nomeji** [jimmywarting/StreamSaver.js#172]
# Problem

You can only download a file once in an insecure context.

# Software

Firefox 73.0.1

# How to reproduce

* Serve "exemple/fetch.html" in an insecure context (basic http server without https)
* Click "Start", download works
* Click "Start" once again without reloading page, download doesn't work

# What I expected

* Download start every time I click start

This is the behaviour in a secure context ([exemple website](https://jimmywarting.github.io/StreamSaver.js/examples/fetch.html))

# Side notes

This issue isn't critical to me since I run my software in a secure context in prod, the issue will only be present in dev environment.

But I would be happy to know if it's fixable. I can make a PR if you think it's fixable.

Issue isn't present on Edge and Chrome.

**Comment by jimmywarting** [comment]
> But I would be happy to know if it's fixable. I can make a PR if you think it's fixable.

That would be lovely. think the problem lies here:

https://github.com/jimmywarting/StreamSaver.js/blob/a72227c1950dcc88088aebcf9e6b664ae81992ea/StreamSaver.js#L114-L120

a potential fix would be to set `mitmTransporter = null` around here maybe
https://github.com/jimmywarting/StreamSaver.js/blob/a72227c1950dcc88088aebcf9e6b664ae81992ea/StreamSaver.js#L220

**Comment by Nomeji** [comment]
Exactly as you said, well done
