### ISSUE TITLE
How to websocket  video stream？ 

### ISSUE THREAD

**Issue by luoHongFSD** [jimmywarting/StreamSaver.js#177]
![image](https://user-images.githubusercontent.com/32594228/89277822-e6cf0280-d677-11ea-91fe-dffe3ec3ad84.png)

how saver to video stream?

```
import streamSaver from "streamsaver";
export default class Recorder {
  constructor(flv, decoder) {
    this.flv = flv;
  }
  start() {
    this.stream = this.flv.$canvas.captureStream(25);
    this.mediaRecorder = new MediaRecorder(this.stream);
    const { readable, writable } = new TransformStream({
      transform: (chunk, ctrl) =>
        chunk.arrayBuffer().then((b) => ctrl.enqueue(new Uint8Array(b))),
    });
    this.writer = writable.getWriter();
    readable.pipeTo(streamSaver.createWriteStream("media.webm"));
    this.mediaRecorder.ondataavailable = (evt) => {
      this.writer.write(evt.data);
    };
    this.mediaRecorder.start();
    return true;
  }
  stop() {
    //this.stopStream(this.stream);
    this.mediaRecorder.stop();
    setTimeout(() => {
      this.writer.close();
    }, 1000);
  }
}
```
But it doesn't work and I don't see the download

**Comment by jimmywarting** [comment]
If it's a WebSocket then maybe you shouldn't use MediaRecorder?
but then again i see that you are using `this.flv.$canvas.captureStream` that indicates that it's a MediaStream, so you should use MediaRecorder.

is ondataavailable emitting any events?

**Comment by luoHongFSD** [comment]
```
import streamSaver from "streamsaver";
export default class Recorder {
  constructor(flv, decoder) {
    this.flv = flv;
    this.writed = false;
  }
  start() {
    this.writed = true;
    this.fileStream = streamSaver.createWriteStream("media.mp4", {
      mitm: "http://10.7.2.43:3001/mitm.html?version=2.0.0",
      size: 1024,
    });
    this.writer = this.fileStream.getWriter();
    return true;
  }

  stop() {
    this.writed = false;
    this.writer.close();
  }

   onMessage(receivedData) {
    this.writer.write(new Blob([receivedData]));
  }
}
```
How to download websocket video stream？
Can you teach me？
Thank you

**Comment by jimmywarting** [comment]
- You should set the mitm throught `streamSaver.mitm = url` not as an option in `createWriteStream(...)`
- you used `http` for you mitm. this might not work for you since service worker can only be used in [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts). either you have to disable the security in your browser or threat your ip as secure.
  - using insecure (http) on your domain still works but the mitm.html still needs to be hosted on a secure context, hence why i made it so it can talk to a service worker via a "man in the middle" iframe
- i bet the size of your video stream isn't 1024 so avoid using size if you don't know how much data you are going to use

mather of facts: just use `streamSaver.createWriteStream("media.mp4")` to start of easy at first and then adv later when you have got it working

- when you are writing chunks to streamSaver it has to receive nothing but [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array)
  - Blob's won't work

```diff
import streamSaver from "streamsaver";
export default class Recorder {
  constructor(flv, decoder) {
    this.flv = flv;
    this.writed = false;
  }
  start() {
    this.writed = true;

+   // Service worker needs a secure context (https) to function.
+   // streamSaver.mitm = "https://10.7.2.43:3001/mitm.html?version=2.0.0";

    this.fileStream = streamSaver.createWriteStream("media.mp4", {
-     This is not a valid option:
-     mitm: "http://10.7.2.43:3001/mitm.html?version=2.0.0",
-     Only use size when you know how much you are going to write:
-     size: 1024,
    });
    this.writer = this.fileStream.getWriter();
    return true;
  }

  stop() {
    this.writed = false;
    this.writer.close();
  }

+  /**
+   * @params {Uint8Array} receivedData This is websocket video stream
+   */
   onMessage(receivedData) {
-   this.writer.write(new Blob([receivedData]));
+   this.writer.write(receivedData);
  }
}
```

now, you could do it your way, but here is just an other example how to pipe streams If your data comes from a [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) then the stream specification has a quite neat [sample showcase of how to turn a websocket into a ReadableStream](https://streams.spec.whatwg.org/#example-rs-push-no-backpressure) from which you then later can [pipeTo](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/pipeTo) streamSaver

```js
function makeReadableWebSocketStream(url) {
  const ws = new WebSocket(url);
  ws.binaryType = "arraybuffer"; // recive all chunks as an ArrayBuffer

  return new ReadableStream({
    start(controller) {
      // enqueue Uint8array's to make this readable stream a "byte stream"
      ws.onmessage = event => controller.enqueue(new Uint8Array(event.data));
      ws.onclose = () => controller.close();
      ws.onerror = () => controller.error(new Error("The WebSocket errored!"));
    },

    cancel() {
      ws.close();
    }
  });
}

// now using it:
const readable = makeReadableWebSocketStream('https://example.com/echo.wss')
const writable = streamSaver.createWriteStream('video.mp4')
readable.pipeTo(writable).then(completeFn, failureFn)
```
just to showcase how Readable and Writable stream can work together

**Comment by jimmywarting** [comment]
fyi: localhost is treated as a secure context

**Comment by luoHongFSD** [comment]
you are too good ! 666
