### ISSUE TITLE
How stream saver work under the hood

### ISSUE THREAD

**Issue by AnhTuan-AiT** [jimmywarting/StreamSaver.js#184]
Hello jimmywarting. I really admire you and the package you have created. I am in need of the function of downloading a zip file that could be larger than 3GB in size from the server with the spring boot backend. Using stream saver, I did it on my computer but I don't know how it works, why when I press the download button the file explorer window doesn't open immediately for me to save the file and let it continue to save the stream data to the file I just created. And when it doesn't open immediately so I specify where I want to save the file, during the time I press download (call API by fetch) until the file explorer opens, where will the stream data  be to save? I hope not to save to RAM. Sorry if my expression is not good but what I want to know is the whole file saving process, when the fetch API fetches the stream data from the server and saves it to the file system on the client. Thank you so much

**Comment by jimmywarting** [comment]
if you download something from the server, use it instead of using streamsaver to emulate what a server dose. 

- streamsaver installs a service worker and intercepts requests and acts like a man in the middle (but only for the downloads)
- streamsaver then sends a postmessage to the service worker along with a readableStream ordering it to intercept `example.com/cat.mp4`
- then a hidden iframe is crated to `example.com/cat.mp4`
- streamsaver then responds with a new Response with some Headers making it download the resource instead. the response also takes the ReadableStream and partially writes data bit by bit.

**Comment by AnhTuan-AiT** [comment]
Thank you for your response,

Now I am having a API for download file which return streaming response
body contain a zip file which 6GB or larger in size. Can you give me a
solution so that I can save this file on the disk of client'computer that
have limit of resources (eg, 4GB RAM in total). I really don't want to and
it is not able to load all file in response body into RAM and wait until
download finish then save it in file systems.I don't know how to do that.
Please give me a hand, I really need a solution to implement this feature

Thank you so much <3

Vào Th 2, 28 thg 9, 2020 vào lúc 18:15 Jimmy Wärting <
notifications@github.com> đã viết:

**Comment by jimmywarting** [comment]
Just add a few response headers and don't use ajax to download it and you will be good to go
https://github.com/eligrey/FileSaver.js/wiki/Saving-a-remote-file#using-http-header

**Comment by AnhTuan-AiT** [comment]
if i don't use ajax, e.g fetch API, how can I can API in server

**Comment by AnhTuan-AiT** [comment]
I found some info, does you mean i should use window.location? I don't know how to use it. Can you explain for me and guide me how to use a method non-ajax to solve my problem? Please give me a hand

**Comment by jimmywarting** [comment]
I don't know how to be more clear to you. but i will try one last time.

if you use ajax, then you take control over how resource is fetched.
to trigger browsers default download from a server then you must navigate to that API endpoint of yours somehow.

But if you are required to send a authentication header then you have a flaw in your design.
if you have had used cookies instead then it would be sent with all other request that you do.
you could solve this in other ways also by adding the authentication token to your url `?token=abc` or adding it using service worker
another solution could be to create a one-time expiring download link that don't need any headers.

your end goal must be to let the user navigate to your URL from where it can download the zip file without sending any custom request headers. and browser have this limitation where it don't allow you to add headers durning navigation (unless you stick them in using service workers)

```js
// create a one time download link
fetch('/api/get-download-link?resourceId=123', {
  headers: { authentication: 'bearer token' }
}).then(res => res.json()).then(json => {
  // navigate to the zip
  location.href = json.download_link
})
```

```html
<a href="/api/download?id=123&token=abc"> download project.zip </a>
<script>
  // or: 
  location.href = '/api/download?id=123&token=abc'
</script>
```

if you would be required to also upload stuff then you would have to use a `<form>` instead.

**Comment by AnhTuan-AiT** [comment]
The way you suggest this already works @jimmywarting :))))))). I did it like this, when the user presses the download button, I call the API on the server to compress the files I need to download into a zip file, create a one-time expiring download link and return it to the user. . I then use the command window.location.href = "one-time expiring download link" then let the browser download the file I need, save it directly to disk on the client computer. Everything is going according to my demand. How wonderful it is. Why did I know how to do this until now :((

Thank you, thank you very much for your enthusiasm to help me. I just want to bother you a little more. Hope to hear from you. I want to understand more deeply what I'm doing. Tỗi xin lỗi vì tôi không biết cách viết code để nó hiển thị như bình luận trên của bạn. I want to ask when I have at hand one-time expiring download link. I use it by calling just one command: 

window.location.href = "one-time expiring download link"

1. So, the first question: Is there any difference between "window.location.href" and "location.href"? Does this work in most browsers today.

2. 
<a href="/api/download?id=123&token=abc"> download project.zip </a>
<script>
  // or: 
  location.href = '/api/download?id=123&token=abc'
</script>

Is this code you are instructing me that we will create a <a> tag, which will display the text "download project.zip". When pressed, the scripting will run and the application will navigate to the file download link. On that link is attached the information I want to send to the server (eg sesion, pass, ...). It's a way I can solve the problem that I want to include credentials or something in general on the server when I want to download the file. I understand that correct?

3. "if you would be required to also upload stuff then you would have to use a <form> instead"
In your statement, I do not fully understand the effect of using <form> tag. Can you give me a sample code about using <form> tag and explain how it works?

4. I guess you are quite tired of questions at this point, this is the last one, do your best!
    //IE11 support
    if (window.navigator.msSaveOrOpenBlob) {
      window.navigator.msSaveBlob(blob, fileName);
    } else {
      // other browser
      let link = window.document.createElement("a");

      link.href = window.URL.createObjectURL(blob);
      link.setAttribute("download", fileName);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      // Second approach but cannot specify saved file name!
      // let file = new File([data], fileName, { type: "application/zip" });
      // let exportUrl = URL.createObjectURL(file);
      // window.location.assign(exportUrl);
      // URL.revokeObjectURL(exportUrl);
  }

As far as I understand they're creating a hidden <a> tag and using it to download the files they need. But I don't know when we will use this. Can you explain it to me?

Again, thank you, thank you very much. I would also apologize if I let my problem bother you and your favorite job too much <3

**Comment by jimmywarting** [comment]
> So, the first question: Is there any difference between "window.location.href" and "location.href"? Does this work in most browsers today.

<details>
<summary>Yes, it works in all browser</summary>

`window.location` is the same as `location`
[window](https://developer.mozilla.org/sv-SE/docs/Web/API/Window) is just a global variable and window can be the same as `globalThis`, `this`, or `self`
if `location` or `foo` is not declared as a variable then the default behavior will be too look for it on `window[variable]`
</details>

> Is this code you are instructing me that we will create tag <a>

Since you decided to go with the route: "creating a one time download link", then you won't need to create a `<a>` link.
You can just use
```js
location.href = json.download_link
```

> if you would be required to also upload stuff then you would have to use a `<form>` tag instead
> ...
> Can you give me a sample code about using `<form>` tag and explain how it works?

<details>
<summary>Example use case: </summary>

- You would like to upload a png file and convert it on the server into a webp format and then save it in one single request.
```html
<form target="/api/upload-convert-and-download" method="POST" enctype="multipart/form-data">
  <input type="file" name="png_file" required>
  <input type="submit">
</form>
```

- Or you would like to export a selection of your database but only want to select the columns you are interested in
```html
<form target="/api/export-tables" method="POST">
  <select multiple name="selected_tabels">
    <option>users</options>
    <option>posts</options>
  </select>
  <input type="text" name="format" value=".csv">
  <input type="submit">
</form>
```

Those are some examples where the download dependent on some parameters. Where you are required to upload stuff and can't use a simple GET request or doing a navigation using `location.href = path` to download something. 
in those cases you must use a `<form>` and submit it instead of using AJAX, this will also cause a navigation and then it will save the file as long as you respond with some "download" headers.

You can also create this form offscreen and populate all the fields manually with javascript and trigger `form.submit()` also if you would like that. 

One limitation of using `<form>`s instead is that you can't send any custom headers. That's why cookies are better suited since it gets sent to the server in every request you do to the server.
The alternative is to also append a authentication token into the form or into the action url

`<input type="hidden" name="authentication" value="token">`
`target="something?authentication=token"`

If you decide to use form and sending a authentication field inside of using headers, then you also wouldn't have to use two request and you don't need to generate a single use download link

</details>


>  I hope it doesn't load the entire file into RAM.

If the browser don't supports service worker then everything will be buffered up in the memory and saved once everything is downloaded - this includes IE and Safari - Blink (chrome, opera, edge) and Firefox support downloading things generated by a service worker and behaves the same way as if you would navigate to a file that is being download.
**This is also why it's better to use the server whenever possible instead of trying to emulate what a server dose using service workers**

> Where is the data stored temporarily from the moment download button is pressed until the file explorer opens

id depends on browser to browser, OS to OS

> I guess you are quite tired of questions at this point

You are right. If i got one penny for everytime I suggest that a server is better then StreamSaver at saving remote files... oboy!
**streamsaver and other alike is mostly for client generated content only**

> // IE11 support

can this browser never die? ppl should stop supporting it and force the user to switch browser - it's almost dead now.

`msSaveBlob` is a IE only thing and not a standard api. msSaveBlob is used to save client generated content only.

The [download](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download) attribute is standardized 
and it instruct browser to download something without the need of download headers while also specifying a file name. this can be used on both remote files, base64 urls and also blob urls

blobUrls aka: `URL.createObjectURL(blob)` is just a references point to some blob you have gotten or created on the client side

And now please: use google, StackOverflow or github search to look for your questions. Many of this have already been answered long before. 

or ask your question on stackoverflow if there isn't any issue about StreamSaver

**Comment by jimmywarting** [comment]
and also. if you already have a blob from somewhere
then it's better to use the method you described in number 5. instead of using `blob.pipeTo(streamSaver.createWriteStream())`

streamSaver is better when you don't have all data at once or you can't hold everything in memory at one point like a camera recording

**Comment by jimmywarting** [comment]
blob can come from file inputs, drag and drop and even from XMLhttpRequest and fetch

Read this: https://stackoverflow.com/questions/38239361/where-is-blob-binary-data-stored/56419176#56419176

**Comment by AnhTuan-AiT** [comment]
Thank you, thank you so much. I wish I could offer you a drink for what you did for me <3
