### ISSUE TITLE
Newest chrome correctly identifies a TypeError of trying to set TransformStream on streamSaver

### ISSUE THREAD

**Issue by evliu** [jimmywarting/StreamSaver.js#191]
In the README, example to set configuration shows
```
// StreamSaver can detect and use the Ponyfill that is loaded from the cdn.
streamSaver.WritableStream = streamSaver.WritableStream
streamSaver.TransformStream = streamSaver.TransformStream
```

according to https://github.com/jimmywarting/StreamSaver.js/blob/416c53046f668b52a96c845c010f721816265906/StreamSaver.js#L109
```
    // Freeze TransformStream object (can only work with native)
    Object.defineProperty(streamSaver, 'TransformStream', {
      configurable: false,
      writable: false,
      value: TransformStream
    })
```
it looks like `streamSaver.TransformStream = ...` shouldn't work anyways, so newest chrome (just released) now throws error **TypeError: Cannot assign to read only property 'TransformStream' of object '#<Object>'**

**Comment by jimmywarting** [comment]
StreamSaver take priority over native implementation cuz it's work better than a polyfilled version cuz they can be transfered to another worker. but in reality, it don't have so much to do with TransformStream as it has with ReadableStream - the important part is that you can have a transferable ReadableStream and not a TransfromStream... Transform Stream is just easier cuz you get both a writable and readable stream (duplex) (just hand the readable to service worker and the writable to the developer)

The real issue is not that chrome started to get support for TransformStream, they just removed the dev- flag for transferable ReadableStream support...

It should be okey to not set the `streamSaver.TransformStream = streamSaver.TransformStream` in fact that should not be mention in the readme... i think.

should be enough with just 
```js
// StreamSaver can detect and use the Ponyfill that is loaded from the cdn.
streamSaver.WritableStream = streamSaver.WritableStream
```

**Comment by evliu** [comment]
Thanks for the good explanation. I'll test it without TransformStream on Monday!

**Comment by evliu** [comment]
Got it fixed on chrome with the info but now has stopped working on IE11. I'll see if I can get it working there too

**Comment by evliu** [comment]
figured out my IE11 issue: sw.js is written in ES6, and IE11 doesn't support arrow functions, in case anyone in the future wonders.
