### ISSUE TITLE
Problem Saving as a PDF

### ISSUE THREAD

**Issue by Muirik** [jimmywarting/StreamSaver.js#215]
Thanks for this great library. I am using Node on the backend and React on the frontend. Presently, I am able to successfully pass down data such as HTML and reconstruct and render it on the frontend  using StreamSaver. However, when I try to render a PDF it is not working. To be sure encoding isn't the issue, I am encoding on the backend and decoding on the frontend via base64. 

To be clear, a PDF does download via the browser, without error, and it is the correct number of pages. However the PDF is always blank.

This is the code I am using on the frontend React app:

  ```js
      let buffer = '';
      dataStream.on('data', (data) => {
        buffer += data;
      });

      dataStream.on('end', () => {
        console.log('STREAM FINISHED');
        const fileStream = streamSaver.createWriteStream('notes.pdf');

        const decodedData = atob(buffer); // base64 decoding
        console.log(decodedData);

        const pdfBlob = new Blob([decodedData]);
        const readableStream = pdfBlob.stream();

        if (window.WritableStream && readableStream.pipeTo) {
          return readableStream
            .pipeTo(fileStream)
            .then(() => console.log('Done writing'));
        }
        // Write (pipe) manually
        const writer = fileStream.getWriter();
        const reader = readableStream.getReader();
        const pump = () =>
          reader
            .read()
            .then(res =>
              res.done ? writer.close() : writer.write(res.value).then(pump)
            );
        pump();
      });
```

**Comment by jimmywarting** [comment]
StreamSaver and other alike is mostly built for client generated content. If you already have the PDF on the server, then i recommend you to download the pdf using nothing but the server instead of emulating one using service worker. (by using content-disposition attachment header)

Beside the way you constructs a blob in the `end` event and later calls `blob.stream()` beats the hole purpose of using StreamSaver in the first place. the hole point of StreamSaver is to save huge data generated on the client side with bits of pieces at the time where you can't hold everything in memory at one point.

If you got a file or a blob already then it's easier to save it using something like FileSaver.js or just manually creating a link with a ObjectURL and a download attribute and trigger a click event. `a[src="blob://..."][download="filename"]`

---

I would also recommend that you avoid using base64 and work directly with uin8arrays or any binary format

**Comment by jimmywarting** [comment]
anyway a more correct approach would be something like this:

```js
const fileStream = streamSaver.createWriteStream('notes.pdf')
const writer = fileStream.getWriter()

dataStream.on('data', (data) => {
  writer.write(data) // should be a Uint8Array
})

dataStream.on('end', () => {
  writer.close()
})
```

**Comment by Muirik** [comment]
I am trying your suggestion now, thanks. By the way, the reason we opted for streamsaver over filesaver is because the download can be pretty large - like 400 documents within a PDF.

**Comment by jimmywarting** [comment]
> I am trying your suggestion now, thanks. By the way, the reason we opted for streamsaver over filesaver is because the download can be pretty large - like 400 documents within a PDF.

Then you shouldn't construct a Blob

**Comment by Muirik** [comment]
Many thanks, Jimmy. Your suggestion worked!
