### ISSUE TITLE
No Video(e.g hls) saving example

### ISSUE THREAD

**Issue by waakobrian** [jimmywarting/StreamSaver.js#266]
Please include (like hls) the video saving example at https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/video-stream.html

**Comment by jimmywarting** [comment]
nah, hls is more complicated. it involves many small chunk files with seperated video resolutions and sperated audio tracks and sperated subtitle tracks.
it's not like one mkv, mp4 or avi file that contains all the data in a single container

it would also require a dependency on something like hls.js to parse the mainifest

streamsaver is for saving one large file only, (dose not handle multiple files that well - would need to arcive everything into one single file in order to save multiple files)
if you want to save a hls then you would probably want to use [whatwg/fs](https://github.com/whatwg/fs), let the user select a directory on the disk and ask for write permission to it.
