### ISSUE TITLE
Save Failure - Network Error (due to Service Worker Restart)

### ISSUE THREAD

**Issue by bhnyc** [jimmywarting/StreamSaver.js#39]
Great work on StreamSaver.js! I'm trying to use this to download and save a large file but I am consistently running across a problem with Chrome where the download fails about 10 minutes in with "Failed - Network Error".  I've done a good amount of debugging and see that Chrome, which manages the Service Worker lifecycle, seems to kill/restart the service worker every 10 minutes or so. Have you run into this issue?

I was able to reproduce it using the your example.html file by simply slowing down the lorum ipsum text generator as follows (I added a 1000 ms timeout):
```js
writer.write(text).then(() => { setTimeout(pump, 1000) })
```
You'll notice that when you generate 30GB, the save fails about 10 minutes in.  Make sure you do not have Developer Tools running as Chrome doesn't restart the service worker when developer tools are open (for troubleshooting purposes).

Any thoughts on how to get around this problem?

**Comment by eligrey** [comment]
I feel like the anti-botnet changes to Service Workers are going to eventually make this a fundamentally unsolvable issue. This may need to be addressed with a standards body.

**Comment by bhnyc** [comment]
Thanks Eli. Is there any way we can potentially solve this through use of event.waitUntil() in the Service Worker?  I see it is being used in the example but doesn't appear to be working as expected (unless I am missing something).

**Comment by DEFENDORe** [comment]
It looks like the browser will kill a ServiceWorker even while using event.waitUntil or event.respondWith to keep it alive. Its a security feature, although I found the last post on this bug report interesting..
[https://bugzilla.mozilla.org/show_bug.cgi?id=1302715](https://bugzilla.mozilla.org/show_bug.cgi?id=1302715)

**Comment by eligrey** [comment]
Idealy, if I had control over the direction of Chrome development, I would change this behavior so that the timeout time limits aren't enforced until detected user idle (e.g. no mouse/keyboard/input activity for X minutes).

**Comment by paulirish** [comment]
@bhnyc can you file a ticket on the chrome issue tracker? I'd like to route this to the right folks.

**Comment by eligrey** [comment]
@paulirish I'll file an issue tomorrow if he hasn't already.

**Comment by bhnyc** [comment]
Sorry for the delay, I just filed a bug here:  https://bugs.chromium.org/p/chromium/issues/detail?id=678798

Feel free to chime in on the bug thread to clarify the problem or provide more support for why this should be allowed.

**Comment by eligrey** [comment]
@bhnyc Thanks. I'll be watching that issue.

**Comment by jimmywarting** [comment]
Me too

**Comment by jimmywarting** [comment]
I'm only speculating now but maybe there is a way for the service worker to be kept alive if we send some sort of activity. like pinging it every x minute from the main thread using a ajax request...

**Comment by bhnyc** [comment]
@jimmywarting I tried a setTimeout loop in the main page that sent a message to the ServiceWorker every 500ms to keep it active. It still got killed after about 5 minutes but was immediately re-spawned to handle the subsequent incoming message (although the kill/re-start broke the download). The fact that it can get re-spawned so quickly seems to support the idea of keeping the original worker active while the page is open.

**Comment by hosseinGanjyar** [comment]
@bhnyc  Please show a code for help to me. thnks

**Comment by jimmywarting** [comment]
@bhnyc solution didn't work. 

But I just thought about another solution/idea that involves partial download. That way the service worker can still restart and manage to save the file. I think it may even work for Firefox.

I don't know if it works with unknown file size. Need to completely refactor the code (switch from using streams to 206 partial response in sw.js)

**Comment by hosseinGanjyar** [comment]
@jimmywarting when u refactor code?

**Comment by jimmywarting** [comment]
I'm quite busy right now with work and other stuff. But i can maybe take a look at it in the weekend. I will create a new issue for partial saving

**Comment by jimmywarting** [comment]
> In my case I think as long as the website with the same scope has a MessageChannel shared with the service worker it would be wrong to terminate the service worker<br>
 > > This usecase is already handled by shared workers.

Maybe we have a solution to prevent service worker restart 👍

**Comment by hosseinGanjyar** [comment]
I dont understand of this solution....
Please describe more.
Thanks

**Comment by Lordiuz** [comment]
@jimmywarting can you help with this solution, please?

**Comment by jimmywarting** [comment]
@Epsilon> hmm. just [tested sending a simple postMessage/heartbeat to sw](https://plnkr.co/edit/XqqQybE7xkccIgXQtTkT?p=preview), seems to work pretty well. 

Then i did the same test by sending a postMessage/heartbeat from a MessageChanel that i had passed onto the sw every 5th sec but that restarted the service worker anyway.

I could have the default live [mitm.html](https://jimmywarting.github.io/StreamSaver.js) ping the sw.js every 4.5. That could solve it for everyone that uses https on there site and haven't changed the mitm url to something else, this group of users wouldn't have to lift a finger.

The others that uses http must rely on a popup wish is immediately closed after transferring the MessageChannel to the sw.js. this group of user must send a dummy ajax request to the sw to avoid having the popup being open all the time. this group of user needs to update streamsaver.js (that also means those who use a custom mitm)

**Comment by kgrzesiu** [comment]
Hi! Thanks for great work on StreamSaver.js! 
I have a similar issue to described here however the files I am downloading are small (I get the Network Failed error right away)
When I run the code in Chrome behind *--disable-web-security* flag, all works fine.
However when deployed to prod, I get the **"Failed - Network error"** on the file. (all requests are 200). 
Any suggestions or at least a way to debug this?

**Comment by jimmywarting** [comment]
@kgrzesiu could you provide a minimal test code/fiddle?

**Comment by kgrzesiu** [comment]
@jimmywarting I am trying to use streamsaver with pako. I am feting the file and using ReadableStream trying to inflate the contents and save it to local file. I have multiple files I am trying to inflate. 
Test code works in development (with --disable-web-security) but not when deployed. (Typescript)

[GZipFileTest.ts.txt](https://github.com/jimmywarting/StreamSaver.js/files/2758916/GZipFileTest.ts.txt)

**Comment by kgrzesiu** [comment]
> @kgrzesiu could you provide a minimal test code/fiddle?

Solved the problem. 
StreamSaver works just fine. The issue was, that the gzip files were empty, which results in Network Fail, since I was not writing anything.... 🥇

**Comment by jimmywarting** [comment]
@kgrzesiu

There is a easier way now to save streams using pipeTo
```js
const links = [
  URL.createObjectURL(new Blob(['fragment1'])),
  URL.createObjectURL(new Blob(['fragment2']))
]

const fileStream = streamSaver.createWriteStream('multifiledownload.txt')

const last = links[links.length-1]
for (link of links) {
  const res = await fetch(link, this.options)
  await res.body.pipeTo(fileStream, { preventClose: link !== last })
}
```

**Comment by kgrzesiu** [comment]
@jimmywarting 
Awesome, thx for taking a look!

**Comment by jimmywarting** [comment]
updated to use a simpler for loop (incase the list contains same item multiple times)

**Comment by jimmywarting** [comment]
Transferable Streams - Woop woop! 
=========

Transferable where [introduced in chrome v73](https://www.chromestatus.com/features/5298733486964736)
I have tested it out in canary and it will ship with the next chrome version (v72 now)

This now means that a `Transform` stream are created, the writeable stream are given to you, and the readable stream is transfered to the service worker. This solves a lot the service worker respond directly with the readable stream and have a 1:1 communication instead of using postMessage

That also means you can now pass in a queueing strategy into the mix and actually use it, like so:
```js
var strategy = new ByteLengthQueuingStrategy({ highWaterMark: 32 * 1024 })
var fileStream = streamsaver.createWriteStream('filename.txt', strategy)
```
then when the buffer is full `writer.write` will return a promise that **actually** waits now to be resolved when the readable stream can take on more data

```js
await writer.write(something) // resolved when bucket is not full
```

it also means that if you pipe a really large file like this

```js
res = await fetch('huge_file')
res.body.pipeTo(fileStream)
```

... you can pause the download and it will actually tell the browser to back of b/c you have to much data in the bucket. so you can download as fast as you can write to the disk.

**What else?**
Oh yea it might mean that the service worker don't have to be alive to transfer all chunks of data with postMessage to the output stream that goes to the disk (it just signals the readable stream to the disk and lets the core do its thing) that might also mean that a service worker reload might not affect the download!!! but i have not tested that yet

**Comment by jimmywarting** [comment]
Oh i forgot... the [web stream polyfill](https://www.npmjs.com/package/web-streams-polyfill) have some disadvantage. they are not transferable. Piping a native stream you get from (eg `Response.body`) don't work together with the polyfill eiter.

**Comment by jimmywarting** [comment]
ok, closing this since there are three solution out there now that should tackle the problem in both 

1) transfarable stream
2) pinging the sw every 29s (before 4,5m) to keep the sw alive  
3) hosting all files yourself can help also.

a forth solution is coming out later and there is an issue for it already (native-filesystem (#73))

if you guys have any objections i can open this again

**Comment by TexKiller** [comment]
@jimmywarting

I have devised a solution for HTTP pages that work on Firefox, but I am unable to test it in Chrome since the Service Worker apparently never dies there, even without the solution.
Do you know of any reason for that to be happening? Do I need to do something specific for the timeout to happen?

**Comment by jimmywarting** [comment]
@TexKiller Just having the devtool open can prevent the SW to close. Pinging the SW every x sec with a postmessage or having an other tab or service that also use the SW at the same time

**Comment by TexKiller** [comment]
@jimmywarting

Nope, can't make Chrome kill the damn Service Worker even once. No devtools, no ping (HTTP), and no other tabs open. I even opened a second window and closed the original one, and it is still alive after two hours.

Did they change something at some point and now the ServiceWorker stays alive until the stream is closed? I did some research and found nothing indicating that. If that is the case, then HTTPS doesn't need the persistent iframe on Chrome anymore, even before transferable streams.

Maybe I should try and find an old version where the Service Worker dies as expected.

**Comment by TexKiller** [comment]
@jimmywarting

Update: Finally got Chrome to kill the Service Worker. Apparently, after you start the keepAlive interval inside the popup the Service Worker never dies, even if you close the popup. Without the keepAlive interval being started the download fails after some minutes.

This behaviour is different from Firefox, and I think it might be a bug on Chrome. On Firefox, even if you start the interval, it stops working after the popup is closed, and the ServiceWorker gets killed after 30 seconds.

Should I put the solution I made to keep the Service Worker alive on HTTP inside a check to see if we are on Firefox, since Chrome doesn't need it? I haven't tested on Opera yet, but I think it might work the same as Chrome, they seem very similar.

**Comment by jimmywarting** [comment]
hmm, don't know. I like to encourage ppl to use https whenever possible. it still works when using http+popups but not as good as when using https so i see it as a progressive degradation or enhancement. 
won't ppl only wonder what the heck the empty popup is for and just close it?
Also the problem might go away by itself when FF makes stream transfarable

**Comment by TexKiller** [comment]
Oh, my solution doesn't keep the popup open, I managed to keep the Service Worker alive using an iframe that starts a Shared Worker, and the Shared Worker is the one that pings the Service Worker with Fetch requests.

It is kind of hacky, but it was the only way that worked on Firefox - if I just make an Ajax or Fetch request from the HTTP page or from HTTPS iframes, the requests were ignored by the Service Worker.

This or another solution is currently required to support Web Extensions on Firefox, since they behave as if they were HTTP there (different from Chrome, where they behave as if they were HTTPS). Without a way to keep the ServiceWorker alive, any Web Extension on Firefox would be incapable of using the library for downloads longer than 30 seconds.
