### ISSUE TITLE
Can I save live audio streams with this JS library?

### ISSUE THREAD

**Issue by Konstantinusz** [jimmywarting/StreamSaver.js#4]
For example online radio streams (live or media libraries). Or should I use the experimental media recording API?

**Comment by jimmywarting** [comment]
Yes you can.

The media recording api is more for Media devices like Webcam/Microphone (and screen)
Live radio stream is in a since more like a data stream

For that reason you need to use the Fetch api to get a readable stream.

If you would use the code like it's now in the master you would write something like this
```javascript
fetch('http://example.com/radio-channel').then(res => {
	saveStream(res.body, 'radio.wav')
})
```

But I haven't decided on a public api yet and there is currently one issue with this method. The radio will keep writing to the disk until the stream closes. And there is no way to close the saving stream while keeping the radio stream still open. For that end i have experiment with another method more similar to NodeJS

It's a bit more code to write yourself but you get more control with that. if you would take i look at the [writable stream](https://github.com/jimmywarting/StreamSaver.js/tree/WritableStream) branch then you instead write it like this:

```javascript
let myFile = fs.createWriteStream('radio.wav')
fetch(url).then(res => {
	let reader = res.body.getReader()
	let pump = () => {
		return reader.read().then(({ value, done }) => {
			if (done) { // incase the stream closes for some reason
				myFile.close()
				return
			}
			myFile.write(value)
			return pump()
		})
	}
	pump() // start the pump

	// called when you want to stop
	// myFile.close()
})
```

And if you need/want to listen to the radio at the same time while recording, then you need to create the audio stream by yourself to instead of just setting the audio[src] to a url... You can look how i use the MediaSource in this [SO question](http://stackoverflow.com/questions/33839210/how-to-listen-for-track-and-artist-when-radio-change-song)

**Comment by jimmywarting** [comment]
Eventually you would be able to write it like this but the fetch api has not implement this yet
```javascript
res.body.pipeTo(myFile)
```

**Comment by Konstantinusz** [comment]
I see, unfortunately a user want to record only a given duration / size of a live stream. Somehow counting the recorded bytes and abort the process at a given byte count would be enough to achieve this goal, assuming that audio bitrate is constant.

**Comment by jimmywarting** [comment]
I know, that's a issue
The initial thought was that it would be as easy as [FileSaver.js](https://github.com/eligrey/FileSaver.js/)
and close the write stream when the read stream closes.

Then after a while experimenting with this myself i found out that you actually sometimes want to keep the read stream open to keep listening on the radio or still show the webcam on the page while not writing something to the disk

So i guess it needs something like a Writeable stream where you can write/pipe/close it your self to be in more controll

**Comment by jimmywarting** [comment]
I have decided to use WritableStream as a public api so you can pipe, close, write among other stuff
Look at the project page (readme) to see some examples

**Comment by jimmywarting** [comment]
There is an example on the project page now
