### ISSUE TITLE
Does this run completely offline in airgap environments?

### ISSUE THREAD

**Issue by Pacerier** [jimmywarting/StreamSaver.js#44]
So I was reading this:

> This will scream high restriction just by mentioning service worker. It's such a powerful tool that it need to run on https but there is a workaround for http sites: popups + 3rd party https site. Who would have guess that? But I won't go into details on how that works. (The idea is to use a middle man to send a dataChannel from http to a serviceWorker that runs on https).

Does it send the data to any server?

Does this run completely offline in airgap environments?

**Comment by jimmywarting** [comment]
It's a twisted answer...
It doesn't completly work offline. It still has to loads the iframe and javascript that lives on github pages.
But no data is being sent to any server you can saftly write 20 GB of data without bandwidth cost or a slow internet speed, since the data will go direckly to the harddrive

You are basically opening up a iframe that has a [service worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) installed on the page in witch the plugin use to communicate with postMessage.

So when you download a file you will actually see it as if the file where downloaded from https://jimmywarting.github.io/xxxxx `github.io` has not read any of the data

If you would like you could take the service worker script and host it on your own domain. then it can work completely offline
