### ISSUE TITLE
NPM module

### ISSUE THREAD

**Issue by thomasbee** [jimmywarting/StreamSaver.js#6]
Could you please distribute StreamSaver.js and its dependencies as an NPM module. I'd like to use it in angular 2 and it would be much nicer as an NPM.

**Comment by jimmywarting** [comment]
I'm about to do that. 
But it's too early for a release. 

I'm still experimenting with the public API and the and there is some few breaking change here and there in the beginning. Haven't tried this for large data (1gb+) yet with backpressure, memory consumption and all that 

The communication between the service worker and StreamSaver.js has to be solid first since there is some site that don't run https and want to use this are forced to use a 3th party website that can host the service worker (in this case the one that lives on gh-pages)
So i need some sort of version control first

Beside, This can't really be used yet until chrome v52 arrives, so no rush.

**Comment by karissa** [comment]
chrome 52 is here! want to publish this to npm? :)

**Comment by jimmywarting** [comment]
Sure, I don't have time right now. I'm about just going away shopping for a bit. But will make this done by the end of the day

**Comment by karissa** [comment]
yay thanks!

**Comment by karissa** [comment]
we're going to use it in http://dat-data.com !

**Comment by jimmywarting** [comment]
https://www.npmjs.com/package/streamsaver
