### ISSUE TITLE
WriteStream File not found error

### ISSUE THREAD

**Issue by lucalas** [jimmywarting/StreamSaver.js#67]
Good morning,
i'm trying to use the library to save basically files created in memory.
The piece of files are stored in array of base64 value that are converted in uint8array, code below (React with Typescript):

```ts
let fr: FileReader = new FileReader();
let myFile = createWriteStream(fileName);
let writer = myFile.getWriter();
let currentDoc: number = 0;

fr.onload = () => {
    let uint8array = FileUtils.Base64Binary.decodeArrayBuffer(fr.result);
    console.log(uint8array);
    writer.write(uint8array).then(() => {
        currentDoc++;
        if (currentDoc === gFile!.docs.length) {
            writer.close();
        } else {
            readDoc();
        }
    });
}

let readDoc = () => {
    let blob: Blob = new Blob([gFile!.docs[currentDoc].encodedFile], { type: "text/plan;charset=utf-8" });
    fr.readAsBinaryString(blob);
}

readDoc();
```

The problem is that when it starts to do write method an error occured and site redirect to a page like:
https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.9707839350708563

that not exists.

I tried to understand what's wrong with my code but didn't find something, can you help me?

**Comment by jimmywarting** [comment]
I would not recommend to use StreamSaver if you already have a blob. 
It's easier to save a blob using something like [FileSaver.js](https://github.com/eligrey/FileSaver.js) instead and has more cross platform support.

I created this so that you can save a very large amount of data generated on the client side. like a generated zip file or a large data transfair with some streaming technology. where RAM memory is not enough 

----

What you are doing is reading the hole blob into the memory as a binary string and then decoding the binary string to a arraybuffer which is a waste of RAM usage and cpu processing. 

Btw, you could just have used `fr.readAsArrayBuffer` directly instead of using `readAsBinaryString` which have been deprecated for a long time and isn't any good to work with. Use `readAsArrayBuffer` when ever possible when working with binary data.

---

Something that i think you don't want to do is ether is concatenating all your files into one large file that can't be read by any program, you are not writing each document to a folder if you think that.

Or if it where your end goal you could just have done this using FileSaver: 
```js
var finalBlob = new Blob(gFile!.docs.map(d => d.encodedFile), { type: "text/plan;charset=utf-8" })
saveAs(finalBlob, filename)
```

**Comment by jimmywarting** [comment]
Also the streamSaver also only works in chrome, so that might be your problem

**Comment by lucalas** [comment]
Ok, i didn't explane correctly what program does:
Each "document" is a piece of file encoded in base64, so i need to reassemble in one file, this is why I want to use your library.
I'll change the flow to don't load every piece of base64 together but for the moment it's ok because I'm just trying to make it work.

For the waste of RAM if I load only a piece of max 10 mb (this is the maximum for each document) i don't think I have a lot of waste of RAM, right? if i'm wrong tell me.
Thanks for the script but i can't use it because I need to assemble and if I load each piece i'll probably have a memory leak.

Btw, I tried using Chrome and i don't know why doesn't work.

**Comment by jimmywarting** [comment]
If you want a good (safe) streaming out of all documents you could do something like this:

```js
function pull(docs, writer) {
  var position = 0
  var chunkLength = 524288
  var fr = new FileReader
  var i = 0
  var blob = docs[i]

  if (!blob) throw Error('Need at least one document')

  fr.onload = () => {
    var uint8array = new Uint8Array(fr.result)
    writer.write(uint8array)
    position += fr.result.byteLength

    if (position === blob.size) {
      i++
      position = 0
    }

    if (docs[i]) {
      fr.readAsArrayBuffer(docs[i].slice(position, position + chunkLength))
    } else {
      writer.close()
    }
  }
  
  fr.readAsArrayBuffer(blob.slice(position, position + chunkLength))
}

docs = [
  new Blob(['abc']),
  new Blob(['def'])
];

docs.length && pull(docs, writer)
```

**Comment by jimmywarting** [comment]
Do your website use http or https?

**Comment by lucalas** [comment]
Everything is fine.
I found the problem, it was my fault and is a really stupid problem:


    let uint8array = FileUtils.Base64Binary.decodeArrayBuffer(fr.result);
    console.log(uint8array);
    writer.write(uint8array)

The decodeArrayBuffer returns me an ArrayBuffer object that i pass direct to writer without the creation of Uint8Array so I just add this:

    let arrayBuffer = FileUtils.Base64Binary.decodeArrayBuffer(fr.result);
    let uint8array = new Uint8Array(arrayBuffer);
    console.log(uint8array);
    writer.write(uint8array)

Now everything works fine.
Sorry for waste of time, I spent a lot of time without find a solution and it was in front of me!
Thanks for your patience!

**Comment by jimmywarting** [comment]
No problem, good luck with your project
