### ISSUE TITLE
MS Edge should now support streams

### ISSUE THREAD

**Issue by shastaxc** [jimmywarting/StreamSaver.js#80]
According to the site you linked in the README, https://developer.microsoft.com/en-us/microsoft-edge/platform/status/streamsapireadablestream/

It looks like streams (readable and writeable) is supported in build 16299, and service workers are now available in build 17063.

I updated Edge to 17134, but when I call streamsaver.supported I still get "false" back.

I have not tested to see if functionality itself will work because I don't want to waste development time if this API doesn't support Edge.

**Comment by jimmywarting** [comment]
Well, I only have Mac. So I can't test it

**Comment by biscoe916** [comment]
@jimmywarting https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

As soon as I have free time, I'll give it a test, but for future, this site makes it super easy to test Edge, and IE on a mac.

**Comment by Pizzacus** [comment]
### [Edge supports Readable Streams... But not constructors](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream#Browser_compatibility)

![image](https://user-images.githubusercontent.com/7659613/55951825-74ebd200-5c58-11e9-8b28-f38fc92524a9.png)

![image](https://user-images.githubusercontent.com/7659613/55949426-de68e200-5c52-11e9-9d98-9f4a067c729d.png)

So I'm pretty sure we can't use them yet, I may be wrong tho, but I couldn't find any way to do anything significant with ReadableStreams on Edge

**Comment by jimmywarting** [comment]
Well, the good news is that Edge will be chromium based soon and have all the goodies chrome have.

**Comment by Pizzacus** [comment]
Idk if these are good news :x 

I don't know how I feel about Chromium being basically the only browser core on the market along with Firefox... But on the other hand... it will certainly make Edge better.......

**Comment by jimmywarting** [comment]
... and webkit (Safari)

**Comment by Pizzacus** [comment]
...oh right

Then webkit is the only browser core with FF since Chromium is based on it, ANYWAY, YOU GET THE IDEA xD

**Comment by jimmywarting** [comment]
nah, they forked webkit and called it blink

**Comment by Pizzacus** [comment]
🤔 So then I guess Safari is ok 👌  <sup><sup>At least on this perspective</sup></sup>

**Comment by jimmywarting** [comment]
Got a little bit of topic :P

**Comment by jimmywarting** [comment]
Well, i tried Edge canary (chromium based) on mac and it works 🎉 
Maybe previous Edge did support it (i don't know)

So it works in every major browser now except for Safari
ironically it has everything that is needed, but it can't download something that is coming from the server worker. it makes a u-turn and decide to save the thing behind the service worker...

To tackle Safari (and maybe other older browser) I have decided to do a graceful degradation to build a blob from the stream and simply use `a[download]` to save it.

So i'm closing this since stream works in (bleeding) edge now.
if not for the stream support then for the blob fallback solution (that is coming soon) 
Can migrate the this issue (blob fallback) over to the safari issue #69
