### ISSUE TITLE
Axios example

### ISSUE THREAD

**Issue by Epictek** [jimmywarting/StreamSaver.js#98]
Does anyone have some example code using Axios instead of fetch?

Thanks in advance.

**Comment by jimmywarting** [comment]
using axois goes against my best practices for building cross web/node apps 
https://github.com/cross-js/cross-js 
+ it's alot of extra overhead

by using axois way of streaming you are probably going to get a node stream? 
They are not native streams and can't therefore be piped or transfered to the disc directly. Meaning you also have to keep the tab and the service worker alive by pinging it every now and then.

This example don't require neither the tab or or the service worker to be alive which is a good thing since you can close the tab #97 
```js
const fileStream = streamSaver.createWriteStream('filename.txt')
const res = await fetch(url, opts)
res.body.pipeTo(fileStream)
```

**Comment by jimmywarting** [comment]
also b/c you want to save something using a network request i'm going to say: just use `content-disposition` attachment header and avoid using streamsaver if possible

**Comment by Epictek** [comment]
Okay, thanks for the help :)
